batch_size: 32
num_epochs: 100
num_transformer_layers: 2
learning_rate: 0.001
max_seq_len: 10
model_save_path: "sft_model.pth"
device: "cpu"
vocab: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '-']
input_dim: 256
num_heads: 8
train_data_file: "data/embeddings/cohere_embeddings_train.json"
val_data_file: "data/embeddings/cohere_embeddings_val.json"

